In [1]:
import numpy as np

In [2]:
x = np.empty((2,2))
x

array([[4.73103752e-310, 0.00000000e+000],
       [4.24399159e-313, 5.94158822e-313]])

In [3]:
x = np.ones((4,2))
x

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [4]:
x=np.full((4,3),3)

In [5]:
p=np.arange(6).reshape(2,3)
a=np.zeros_like(p)
a

array([[0, 0, 0],
       [0, 0, 0]])

In [6]:
p=np.arange(8).reshape(2,4)
x=np.ones_like(p)
x

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [7]:
new_list=[1,2,3,4]
K=np.array(new_list)
K

array([1, 2, 3, 4])

In [8]:
b=np.arange(10,50)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [9]:
b=np.arange(0,9).reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
b=np.eye(3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
x = np.random.random(30)
mean = x.mean()

print("array given: ", x)
print("Mean  : ", mean)

array given:  [0.10605643 0.77952018 0.83015914 0.51319239 0.01924771 0.06853112
 0.66301462 0.719622   0.82376844 0.76944261 0.56405631 0.12300377
 0.78993739 0.81354545 0.32850452 0.43454799 0.13720874 0.24845672
 0.56121376 0.62351072 0.08534324 0.96962925 0.21085285 0.69189508
 0.35987569 0.69218516 0.78721614 0.50688318 0.73181631 0.17136852]
Mean  :  0.5041201809023692


In [12]:
b=np.random.random((10,10))
min=b.min()
max=b.max()
print("Array: ", b)
print("Min:", min)
print("Max:", max)

Array:  [[3.90131126e-01 6.01014745e-02 1.81337946e-01 4.54043206e-04
  7.82715036e-01 4.96447856e-01 8.34496826e-02 8.27165385e-01
  2.11158789e-01 5.26086034e-01]
 [9.91746985e-01 2.77048019e-02 7.33157983e-01 1.76035414e-01
  8.37854184e-02 9.38400804e-02 1.88338671e-01 7.36697872e-01
  7.62987355e-01 8.93139388e-01]
 [8.94789540e-01 5.96654468e-01 3.21279804e-02 8.29543220e-01
  7.90802106e-01 7.39860993e-01 7.08734543e-01 9.48056781e-01
  5.03381461e-01 5.16899359e-01]
 [5.50274799e-01 9.07616916e-02 7.99707566e-01 2.83742213e-01
  6.72457770e-01 4.39718248e-01 1.69403977e-02 5.63876657e-01
  9.00850026e-01 8.91447480e-01]
 [3.40085770e-01 7.96572679e-01 9.05332922e-01 8.70598295e-01
  4.24870368e-01 7.02305064e-01 8.46657291e-01 5.91073689e-02
  1.73926674e-01 1.37496897e-01]
 [4.08956739e-01 3.99777328e-01 3.15146416e-02 5.75665496e-01
  3.91451973e-01 4.47937568e-01 6.33240814e-01 7.64250413e-01
  5.80421559e-01 4.66960110e-01]
 [8.56437354e-01 7.83403915e-01 6.54363616e-01 5.4

In [13]:
b=np.zeros(10)
b[4]=1
print("Updated :", b)

Updated : [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [14]:
b=np.array([1,2,0,0,4,0])
rev=b[::-1]
print("Original: ", b)
print("reversed: ", rev)

Original:  [1 2 0 0 4 0]
reversed:  [0 4 0 0 2 1]


In [15]:
b=np.zeros((5,5),dtype=int)
b[0,:]=1 #top
b[-1,:]=1 #bottom
b[:,0]=1 #left
b[:,-1]=1 #right
print("1 on border and 0 inside : ",b)

1 on border and 0 inside :  [[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [16]:
b=np.zeros((8,8))
b[1::2,::2]=1
b[::2,1::2]=1
b

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [17]:
x=np.array([[1,2],[3,5]])
y=np.array([[5,6],[7,8]])
x3 = np.array([9,10])
y3 = np.array([11,12])
print("x: \n",x)
print("y: \n",y)
add=x+y
add3=x3+y3
print("Adding x+y: \n",add)
print("x3: \n",x3)
print("y3: \n",y3)
print("adding x3+y3: ",add3)

x: 
 [[1 2]
 [3 5]]
y: 
 [[5 6]
 [7 8]]
Adding x+y: 
 [[ 6  8]
 [10 13]]
x3: 
 [ 9 10]
y3: 
 [11 12]
adding x3+y3:  [20 22]


In [18]:
sub=x-y
sub3=x3-y3
print("subtracting y from x: ",sub)
print("subtracting y3 from x3: ",sub3)

subtracting y from x:  [[-4 -4]
 [-4 -3]]
subtracting y3 from x3:  [-2 -2]


In [19]:
mul_x=x*2
mul_x
mul_y=y*2
mul_y
mul_x3=x3*2
mul_x3
mul_y3=y3*2
mul_y3

array([22, 24])

In [20]:
sq_x=np.square(x)
print("squaring x: \n",sq_x )
sq_y=np.square(y)
print("squaring y: \n",sq_y )
sq_x3=np.square(x3)
print("squaring x3: \n",sq_x3 )
sq_y3=np.square(y3)
print("squaring y3: \n",sq_y3 )

squaring x: 
 [[ 1  4]
 [ 9 25]]
squaring y: 
 [[25 36]
 [49 64]]
squaring x3: 
 [ 81 100]
squaring y3: 
 [121 144]


In [21]:
result = np.dot(x3, y3)
result
result_1 = np.dot(x, x3)
result_1
result_2 = np.dot(x, y)
result_2

array([[19, 22],
       [50, 58]])

In [22]:
a=np.concatenate((x,y),axis=1)
print(a)
a=np.vstack((x3,y3))
print(a)

[[1 2 5 6]
 [3 5 7 8]]
[[ 9 10]
 [11 12]]


In [23]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x3 = np.array([[7, 8, 9], [10, 11, 12]])

try:
    result = np.concatenate((x, x3))
    print("Concatenation result:\n", result)
except ValueError as e:
    print("Error during concatenation:", e)

Concatenation result:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [24]:
A1=np.array([[3,4],[7,8]])
B1=np.array([[5,3],[2,1]])
A_inverse=np.linalg.inv(A1)
result=np.dot(A1,A_inverse)
identity_matrix=np.eye(2)
print("Matrix A1:\n", A1)
print("Inverse of A1 (A^-1):\n", A_inverse)
print("Product of A1 and A^-1 (A.A^-1):\n", result)
print("Identity Matrix:\n", identity_matrix)
y=np.allclose(result,identity_matrix)
print("Is A.A^-1 equal to identity matrix?->",y)

Matrix A1:
 [[3 4]
 [7 8]]
Inverse of A1 (A^-1):
 [[-2.    1.  ]
 [ 1.75 -0.75]]
Product of A1 and A^-1 (A.A^-1):
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Identity Matrix:
 [[1. 0.]
 [0. 1.]]
Is A.A^-1 equal to identity matrix?-> True


In [25]:
A1B1 = np.dot(A1, B1)
B1A1 = np.dot(B1, A1)
print("A1B1 (A1 * B1):\n", A1B1)
print("B1A1 (B1 * A1):\n", B1A1)
are_equal=np.array_equal(A1B1,B1A1)
print(" Is A1B1 = B1A1? ",are_equal)

A1B1 (A1 * B1):
 [[23 13]
 [51 29]]
B1A1 (B1 * A1):
 [[36 44]
 [13 16]]
 Is A1B1 = B1A1?  False


In [26]:
A1 = np.array([[1, 2], [3, 4]])
B1 = np.array([[5, 6], [7, 8]])
AB=np.dot(A1,B1)
AB_T=AB.T
B_T=B1.T
A_T=A1.T
BT_AT=np.dot(B_T,A_T)
print("AB:\n", AB)
print("(AB)^T:\n", AB_T)
print("B^T:\n", B_T)
print("A^T:\n", A_T)
print("B^T * A^T:\n", BT_AT)
is_equal=np.array_equal(AB_T,BT_AT)
print("Is (AB)^T equal to B^T * A^T? ", is_equal)

AB:
 [[19 22]
 [43 50]]
(AB)^T:
 [[19 43]
 [22 50]]
B^T:
 [[5 7]
 [6 8]]
A^T:
 [[1 3]
 [2 4]]
B^T * A^T:
 [[19 43]
 [22 50]]
Is (AB)^T equal to B^T * A^T?  True


In [27]:
A1=np.array([[2,-3,1], [1,-1,2], [3,1,-1]])
B1=np.array([-1,-3,9])
A_inverse=np.linalg.inv(A1)
x=np.dot(A_inverse,B1)
print( A1)
print( B1)
print( A_inverse)
print( x)

[[ 2 -3  1]
 [ 1 -1  2]
 [ 3  1 -1]]
[-1 -3  9]
[[ 0.05263158  0.10526316  0.26315789]
 [-0.36842105  0.26315789  0.15789474]
 [-0.21052632  0.57894737 -0.05263158]]
[ 2.  1. -2.]


In [28]:
import time
l3=list(range(1,1000001))
l4=list(range(1,1000001))
start_time= time.time()
result_list=[a+b for a, b in zip(l3,l4)]
python_time=time.time()-start_time
print(" Python lists time:", python_time, "seconds")
#numpy arrays:
a3=np.arange(1,1000001)
a4=np.arange(1,1000001)

start_time=time.time()
result_array=a3+a4
numpy_time=time.time()-start_time
print(" NumPy arrays time:", numpy_time, "seconds")

 Python lists time: 0.16620445251464844 seconds
 NumPy arrays time: 0.005593776702880859 seconds


In [29]:
start_time=time.time()
result_list=[a*b for a,b in zip(l3,l4)]
python_time=time.time()-start_time
print("multiplication using Python lists time:", python_time, "seconds")

start_time = time.time()
result_array = a3 * a4
numpy_time = time.time() - start_time
print(" multiplication using NumPy arrays:", numpy_time, "seconds")

multiplication using Python lists time: 0.10312128067016602 seconds
 multiplication using NumPy arrays: 0.005259275436401367 seconds


In [30]:
start_time = time.time()
dot_product_list = sum(a * b for a, b in zip(l3, l4))
python_time = time.time() - start_time
print( python_time, "seconds")



start_time = time.time()
dot_product_numpy = np.dot(a3, a4)
numpy_time = time.time() - start_time
print( numpy_time, "seconds")

0.21556711196899414 seconds
0.002372264862060547 seconds


In [31]:
import time
import numpy as np

# Python lists
m3 = [[i for i in range(100)] for j in range(100)]
m4 = [[i for i in range(100)] for j in range(100)]

start_time = time.time()
result_matrix = [[sum(m3[i][k] * m4[k][j] for k in range(100)) for j in range(100)] for i in range(100)]
python_time = time.time() - start_time
print(" Python lists time:", python_time, "seconds")

# Matrix multiplication using NumPy
m3_np = np.random.rand(100, 100)
m4_np = np.random.rand(100, 100)

start_time = time.time()
result_matrix_np = np.dot(m3_np, m4_np)
numpy_time = time.time() - start_time
print("MNumPy arrays time:", numpy_time, "seconds")

 Python lists time: 0.168212890625 seconds
MNumPy arrays time: 0.000385284423828125 seconds
